services:
  # Celery worker service
  celery-worker:
    image: kharjam/celery-communication-service:v1.0.0
    container_name: kharjam-communication-service-celery-worker
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ./app/logs:/communication_service/app/logs
      - ./.env:/communication_service/.env
    environment:
      - PYTHONPATH=/communication_service
    restart: unless-stopped
    networks:
      - rabbitmq-network
      - redis-network

  # FastAPI application service
  communication-service:
    image: kharjam/communication-service:v1.0.0
    container_name: kharjam-communication-service
    build: .
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./app/logs:/communication_service/app/logs
      - ./.env:/communication_service/.env
    environment:
      - PYTHONPATH=/communication_service
    restart: unless-stopped
    networks:
      - rabbitmq-network
      - redis-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rabbitmq-network:
    external: true
    name: rabbitmq_rabbitmq-network
  redis-network:
    external: true
    name: redis_network